import { headers } from 'next/headers';
import ClientProviders from './ClientProviders';
import "./globals.css"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const hdrs = headers();
  console.log('headers', hdrs.get('host'));
  return (
    <html lang="en">
      <head />
      <body>
        <ClientProviders googleClient={process.env.GOOGLE_ID ?? ''}>
          {children}
        </ClientProviders>
      </body>
    </html>
  )
}
